version: 2
updates:
  - package-ecosystem: cargo
    directories: 
      - "/"
      - "tests/extendrtests/src/rust/"
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
