// DO NOT EDIT BY HAND.
// GENERATED BY `rextendr::use_extendr()`.
// This post-build binary is required to generate `R/extendr-wrappers.R`.
use extendrtests::R_WRAPPERS_DEPS as DEPS;
use extendrtests::R_WRAPPERS_IMPLS as IMPLS;
use extendrtests::R_WRAPPERS_IMPL_DEPS as IMPL_DEPS;
use extendrtests::R_WRAPPERS_PARTS as PARTS;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let wrapper_path = "../R/extendr-wrappers.R";
    write_wrappers(wrapper_path, PARTS, IMPLS, DEPS, IMPL_DEPS)
        .map_err(|e| format!("failed to write {wrapper_path}: {e}"))?;
    Ok(())
}

fn write_wrappers(
    path: &str,
    parts: &[&str],
    impls: &[&str],
    deps: &[&[&str]],
    impl_deps: &[&[&str]],
) -> std::io::Result<()> {
    use std::io::Write;

    let mut f = std::io::BufWriter::new(std::fs::File::create(path)?);

    f.write_all(
        b"# ---- AUTO-GENERATED FILE - DO NOT EDIT ----
# This file is generated by the extendr proc-macro during package build.
# Any manual changes will be overwritten.
#
# To regenerate, rebuild the package.
# nolint start
# nocov start

#' @usage NULL
#' @useDynLib extendrtests, .registration = TRUE
NULL

",
    )?;

    let all = parts
        .iter()
        .chain(deps.iter().flat_map(|d| d.iter()))
        .chain(impls.iter())
        .chain(impl_deps.iter().flat_map(|d| d.iter()));

    let mut seen = std::collections::HashSet::<&str>::new();
    for s in all {
        let trimmed = s.trim();
        if seen.insert(trimmed) {
            f.write_all(trimmed.as_bytes())?;
            f.write_all(b"\n\n")?;
        }
    }

    f.write_all(b"# nocov end\n# nolint end\n")?;
    Ok(())
}
