# Build-time helper: invoked by Rscript during package build to call
# `wrap__make_<modname>_wrappers` (which `extendr_module!` emits as
# extern "C") and write `R/extendr-wrappers.R`. See Makevars.in.

dyn.load(file.path("rust", paste0("document", .Platform$dynlib.ext)))

cat(
  "# Generated by extendr: Do not edit by hand\n",
  "# nolint start\n\n",
  "#' @usage NULL\n",
  "#' @useDynLib extendrtests, .registration = TRUE\n",
  "NULL\n\n",
  .Call("write_wrappers", TRUE, "extendrtests"),
  "# nolint end\n",
  sep = "",
  file = "../R/extendr-wrappers.R"
)
