# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_extendrtests_wrappers", use_symbols = TRUE, package_name = "extendrtests")

#' @docType package
#' @usage NULL
#' @useDynLib extendrtests, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

#' Do nothing.
#' @export
do_nothing <- function() invisible(.Call(wrap__do_nothing))

#' Convert a double scalar to itself
#' @param x a number
#' @export
double_scalar <- function(x) .Call(wrap__double_scalar, x)

#' Convert an int scalar to itself
#' @param x a number
#' @export
int_scalar <- function(x) .Call(wrap__int_scalar, x)

#' Convert a bool scalar to itself
#' @param x a number
#' @export
bool_scalar <- function(x) .Call(wrap__bool_scalar, x)

#' Convert a string to itself
#' @param x a string
#' @export
char_scalar <- function(x) .Call(wrap__char_scalar, x)

#' Convert a vector of strings to itself
#' @param x a vector of strings
#' @export
char_vec <- function(x) .Call(wrap__char_vec, x)

#' Test whether `_arg` parameters are treated correctly in R
#' Executes \code{`_x` - `_y`}
#' @param _x an integer scalar, ignored
#' @param `_y` an integer scalar, ignored
#' @export
special_param_names <- function(`_x`, `_y`) .Call(wrap__special_param_names, `_x`, `_y`)

#' Test wrapping of special function name
#' @name f__00__special_function_name
#' @export
`__00__special_function_name` <- function() invisible(.Call(wrap____00__special_function_name))

#' Return string `"Hello world!"` to R.
#' @export
hello_submodule <- function() .Call(wrap__hello_submodule)

vec_generic_class <- function(v) .Call(wrap__vec_generic_class, v)

#' Class for testing (exported)
#' @examples
#' x <- MyClass$new()
#' x$a()
#' x$set_a(10)
#' x$a()
#' @export
MyClass <- new.env(parent = emptyenv())

MyClass$new <- function() .Call(wrap__MyClass__new)

MyClass$set_a <- function(x) invisible(.Call(wrap__MyClass__set_a, self, x))

MyClass$a <- function() .Call(wrap__MyClass__a, self)

MyClass$me <- function() .Call(wrap__MyClass__me, self)

#' @rdname MyClass
#' @usage NULL
#' @export
`$.MyClass` <- function (self, name) { func <- MyClass[[name]]; environment(func) <- environment(); func }

`__MyClass` <- new.env(parent = emptyenv())

`__MyClass`$new <- function() .Call(wrap____MyClass__new)

`__MyClass`$`__name_test` <- function() invisible(.Call(wrap____MyClass____name_test, self))

#' @export
`$.__MyClass` <- function (self, name) { func <- `__MyClass`[[name]]; environment(func) <- environment(); func }

#' Class for testing (unexported)
MyClassUnexported <- new.env(parent = emptyenv())

MyClassUnexported$new <- function() .Call(wrap__MyClassUnexported__new)

MyClassUnexported$a <- function() .Call(wrap__MyClassUnexported__a, self)

#' @export
`$.MyClassUnexported` <- function (self, name) { func <- MyClassUnexported[[name]]; environment(func) <- environment(); func }

#' Class for testing (exported)
#' @examples
#' x <- MySubmoduleClass$new()
#' x$a()
#' x$set_a(10)
#' x$a()
#' @export
MySubmoduleClass <- new.env(parent = emptyenv())

MySubmoduleClass$new <- function() .Call(wrap__MySubmoduleClass__new)

MySubmoduleClass$set_a <- function(x) invisible(.Call(wrap__MySubmoduleClass__set_a, self, x))

MySubmoduleClass$a <- function() .Call(wrap__MySubmoduleClass__a, self)

MySubmoduleClass$me <- function() .Call(wrap__MySubmoduleClass__me, self)

#' @rdname MySubmoduleClass
#' @usage NULL
#' @export
`$.MySubmoduleClass` <- function (self, name) { func <- MySubmoduleClass[[name]]; environment(func) <- environment(); func }

GenericClass <- new.env(parent = emptyenv())

GenericClass$new <- function(a) .Call(wrap__GenericClass__new, a)

#' @export
`$.GenericClass` <- function (self, name) { func <- GenericClass[[name]]; environment(func) <- environment(); func }

