name: Other
description: Something that doesn't fit the other categories
title: ""
body:
  - type: checkboxes
    id: existing-issue
    attributes:
      label: Pre-flight checklist
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
