
use libR_sys::*;
use rapi::*;


// Unsafe R wrapper - will be generated by r_bindgen in the future.
#[no_mangle]
pub extern fn hello_wrapper() -> SEXP {
    unsafe{
        r!(hello()).get()
    }
}

// Safe Rust code.
fn hello() -> &'static str {
    "hello"
}

