//! Respond to user interrupts (Ctrl-C / Esc) from long-running Rust code.
//!
//! R only notices an interrupt when native code asks. This module provides the two
//! ways of asking that are safe from Rust:
//!
//! - [`interrupt_requested`] polls and returns a `bool`. Use it when you want to stop
//!   early but still return a (partial) value to R.
//! - [`check_user_interrupt`] polls and, if an interrupt is pending, unwinds the Rust
//!   stack up to the enclosing `#[extendr]` wrapper, which then re-signals the
//!   interrupt to R. All Rust destructors run on the way. This mirrors
//!   `Rcpp::checkUserInterrupt()` and `cpp11::check_user_interrupt()`.
//!
//! Neither function ever lets R `longjmp` across a Rust frame: the interrupt is
//! detected inside [`extendr_ffi::R_ToplevelExec`], which absorbs the jump in C code
//! that owns nothing, and it is handed back to R only from the wrapper after all Rust
//! frames of the call are gone.
//!
//! Both functions must be called on R's main thread, from code that is (directly or
//! indirectly) running inside an `#[extendr]` function.
//!
//! ```ignore
//! #[extendr]
//! fn slow_sum(n: i32) -> f64 {
//!     let mut acc = 0.0;
//!     for i in 0..n {
//!         if i % 1000 == 0 {
//!             check_user_interrupt();
//!         }
//!         acc += f64::from(i);
//!     }
//!     acc
//! }
//! ```
use crate::single_threaded;
use extendr_ffi::{R_CheckUserInterrupt, R_ToplevelExec, Rboolean, Rf_onintr};
use std::os::raw::c_void;

/// Payload of the unwind started by [`check_user_interrupt`].
///
/// The `#[extendr]` wrapper recognises this payload and re-signals the interrupt to R
/// instead of raising an error. If you catch it with `std::panic::catch_unwind`, pass it
/// on with `std::panic::resume_unwind`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct UserInterrupt;

impl std::fmt::Display for UserInterrupt {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("user interrupt")
    }
}

/// Poll R for a pending user interrupt without unwinding.
///
/// Returns `true` if the user asked to interrupt the computation. The pending interrupt
/// is consumed: R will not raise it on its own afterwards, so it is up to the caller to
/// stop the computation. Returns `false` if there is nothing pending.
///
/// This also lets GUI front-ends process pending events, so avoid calling it on every
/// iteration of a tight loop; every few hundred or thousand iterations is typical.
pub fn interrupt_requested() -> bool {
    unsafe extern "C" fn check(_data: *mut c_void) {
        // May longjmp. The jump is caught by `R_ToplevelExec` and this frame owns nothing.
        R_CheckUserInterrupt();
    }
    single_threaded(|| unsafe {
        R_ToplevelExec(Some(check), std::ptr::null_mut()) == Rboolean::FALSE
    })
}

/// Check for a pending user interrupt and, if there is one, stop the current
/// `#[extendr]` call.
///
/// When an interrupt is pending this function does not return: it unwinds the Rust
/// stack (running every destructor) up to the generated wrapper of the enclosing
/// `#[extendr]` function, which re-signals the interrupt to R. In R the result is the
/// usual `interrupt` condition, so `tryCatch(..., interrupt = )` and friends work.
///
/// Prefer [`interrupt_requested`] if you want to return a partial result instead.
pub fn check_user_interrupt() {
    if interrupt_requested() {
        // `resume_unwind` does not invoke the panic hook: an interrupt is not a bug and
        // must not print a Rust panic message.
        std::panic::resume_unwind(Box::new(UserInterrupt));
    }
}

/// Hand a previously detected user interrupt back to R.
///
/// Used by the code generated by `#[extendr]` once every Rust frame of the call has
/// been unwound. Performs a `longjmp` unless interrupts are suspended, in which case
/// R records the interrupt as pending and this returns normally.
///
/// # Safety
/// Must be called on R's main thread with no Rust frame that owns resources between the
/// caller and R, exactly like [`crate::throw_r_error`].
#[doc(hidden)]
pub unsafe fn resignal_user_interrupt() {
    Rf_onintr();
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{self as extendr_api, prelude::*};
    use extendr_engine::with_r;

    extern "C" {
        fn raise(sig: std::os::raw::c_int) -> std::os::raw::c_int;
    }
    const SIGINT: std::os::raw::c_int = 2;

    // `raise(SIGINT)` is process-wide, so the R API lock is held from the raise until the
    // poll consumes the interrupt; otherwise another test thread inside R could pick it up.
    #[test]
    fn interrupt_requested_reports_and_consumes_a_pending_interrupt() -> crate::Result<()> {
        with_r(|| {
            single_threaded(|| {
                assert!(!interrupt_requested());
                unsafe { raise(SIGINT) };
                assert!(interrupt_requested(), "pending interrupt not detected");
                assert!(!interrupt_requested(), "interrupt was not consumed");
                // R is still usable afterwards.
                assert_eq!(eval_string("1 + 1")?, r!(2.0));
                Ok(())
            })
        })
    }

    #[test]
    fn check_user_interrupt_unwinds_with_typed_payload_and_runs_drop() {
        struct SetOnDrop<'a>(&'a std::cell::Cell<bool>);
        impl Drop for SetOnDrop<'_> {
            fn drop(&mut self) {
                self.0.set(true);
            }
        }
        with_r(|| -> crate::Result<()> {
            let dropped = std::cell::Cell::new(false);
            let res = single_threaded(|| {
                std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
                    let _guard = SetOnDrop(&dropped);
                    unsafe { raise(SIGINT) };
                    check_user_interrupt();
                }))
            });
            let payload = res.expect_err("check_user_interrupt did not unwind");
            assert!(payload.is::<UserInterrupt>());
            assert!(dropped.get(), "destructor did not run during unwind");
            Ok(())
        })
        .unwrap();
    }
}
