#!/usr/bin/env bash
# Regenerate issues.md from the GitHub origin's open issues.
#
# Run manually with `just issues`. Requires the `gh` CLI logged in
# (`gh auth status` should report success).
#
# Fail-soft: if `gh` is missing, unauthenticated, or offline, this
# leaves issues.md alone and exits 0.

set -euo pipefail

root="$(git rev-parse --show-toplevel)"
out="${root}/issues.md"
tmp="$(mktemp "${TMPDIR:-/tmp}/issues.XXXXXX.md")"
trap 'rm -f "$tmp"' EXIT

if ! command -v gh >/dev/null 2>&1; then
    echo "[update-issues] gh CLI not installed; leaving issues.md unchanged" >&2
    exit 0
fi

if ! gh auth status >/dev/null 2>&1; then
    echo "[update-issues] gh not authenticated; leaving issues.md unchanged" >&2
    exit 0
fi

if ! issues="$(gh issue list \
        --state open \
        --limit 500 \
        --json number,title,labels,createdAt,updatedAt,author,url,body,comments,assignees \
        2>/dev/null)"; then
    echo "[update-issues] gh issue list failed (offline?); leaving issues.md unchanged" >&2
    exit 0
fi

count="$(printf '%s' "$issues" | jq 'length')"
repo="$(gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null || echo 'origin')"
now="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

{
    echo "# Open issues — ${repo}"
    echo
    echo "_Auto-generated by \`scripts/update-issues.sh\` on ${now}._"
    echo "_Regenerate with \`just issues\`. Do not edit by hand._"
    echo
    echo "**${count} open issue(s).**"
    echo
    if [ "$count" -eq 0 ]; then
        echo "_No open issues._"
    else
        printf '%s' "$issues" | jq -r '
          sort_by(.number) | reverse | .[] |
          "## #\(.number) — \(.title)\n" +
          "\n" +
          "- **URL:** \(.url)\n" +
          "- **Author:** @\(.author.login // "unknown")\n" +
          "- **Created:** \(.createdAt)\n" +
          "- **Updated:** \(.updatedAt)\n" +
          "- **Comments:** \(.comments | length)\n" +
          "- **Assignees:** " + (if (.assignees | length) > 0 then ([.assignees[].login] | map("@" + .) | join(", ")) else "_none_" end) + "\n" +
          "- **Labels:** " + (if (.labels | length) > 0 then ([.labels[].name] | join(", ")) else "_none_" end) + "\n" +
          "\n" +
          (if (.body // "" | length) > 0 then .body else "_(no body)_" end) +
          "\n\n---\n"
        '
    fi
} > "$tmp"

mv "$tmp" "$out"
trap - EXIT
echo "[update-issues] wrote ${out} (${count} open issue(s))"
