#!/usr/bin/env bash
# Regenerate OPEN-PR.md from the GitHub origin's open pull requests.
#
# Run manually with `just open-prs`. Requires the `gh` CLI logged in
# (`gh auth status` should report success).
#
# Fail-soft: if `gh` is missing, unauthenticated, or offline, this
# leaves OPEN-PR.md alone and exits 0.

set -euo pipefail

root="$(git rev-parse --show-toplevel)"
out="${root}/OPEN-PR.md"
tmp="$(mktemp "${TMPDIR:-/tmp}/OPEN-PR.XXXXXX.md")"
trap 'rm -f "$tmp"' EXIT

if ! command -v gh >/dev/null 2>&1; then
    echo "[update-open-prs] gh CLI not installed; leaving OPEN-PR.md unchanged" >&2
    exit 0
fi

if ! gh auth status >/dev/null 2>&1; then
    echo "[update-open-prs] gh not authenticated; leaving OPEN-PR.md unchanged" >&2
    exit 0
fi

if ! prs="$(gh pr list \
        --state open \
        --limit 500 \
        --json number,title,labels,createdAt,updatedAt,author,url,body,isDraft,mergeable,baseRefName,headRefName,reviewDecision,statusCheckRollup,reviewRequests,comments,additions,deletions,changedFiles \
        2>/dev/null)"; then
    echo "[update-open-prs] gh pr list failed (offline?); leaving OPEN-PR.md unchanged" >&2
    exit 0
fi

count="$(printf '%s' "$prs" | jq 'length')"
repo="$(gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null || echo 'origin')"
now="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

{
    echo "# Open pull requests — ${repo}"
    echo
    echo "_Auto-generated by \`scripts/update-open-prs.sh\` on ${now}._"
    echo "_Regenerate with \`just open-prs\`. Do not edit by hand._"
    echo
    echo "**${count} open PR(s).**"
    echo
    if [ "$count" -eq 0 ]; then
        echo "_No open pull requests._"
    else
        # One-line index for fast scanning
        echo "## Index"
        echo
        printf '%s' "$prs" | jq -r '
          sort_by(.number) | reverse | .[] |
          "- [#\(.number)](\(.url)) " +
          (if .isDraft then "*(draft)* " else "" end) +
          "— \(.title) " +
          "— @\(.author.login // "unknown") " +
          "— `\(.headRefName) → \(.baseRefName)` " +
          "— review: \(.reviewDecision // "PENDING") " +
          "— CI: " + (
              (.statusCheckRollup // []) as $r |
              if ($r | length) == 0 then "n/a"
              else
                  ([$r[] | (.conclusion // .state // "PENDING")] | group_by(.) |
                   map({state: .[0], n: length}) |
                   map("\(.state):\(.n)") | join(","))
              end
          ) +
          " — Δ +\(.additions // 0)/-\(.deletions // 0) (\(.changedFiles // 0) file(s))"
        '
        echo
        echo "---"
        echo
        # Detailed entries
        printf '%s' "$prs" | jq -r '
          sort_by(.number) | reverse | .[] |
          "## #\(.number) — \(.title)" + (if .isDraft then " *(draft)*" else "" end) + "\n" +
          "\n" +
          "- **URL:** \(.url)\n" +
          "- **Author:** @\(.author.login // "unknown")\n" +
          "- **Branches:** `\(.headRefName)` → `\(.baseRefName)`\n" +
          "- **Created:** \(.createdAt)\n" +
          "- **Updated:** \(.updatedAt)\n" +
          "- **Draft:** \(.isDraft)\n" +
          "- **Mergeable:** \(.mergeable // "UNKNOWN")\n" +
          "- **Review decision:** \(.reviewDecision // "PENDING")\n" +
          "- **Requested reviewers:** " + (
              (.reviewRequests // []) as $r |
              if ($r | length) > 0 then ([$r[] | (.login // .name // "?")] | map("@" + .) | join(", ")) else "_none_" end
          ) + "\n" +
          "- **CI status:** " + (
              (.statusCheckRollup // []) as $r |
              if ($r | length) == 0 then "_n/a_"
              else
                  ([$r[] | (.conclusion // .state // "PENDING")] | group_by(.) |
                   map({state: .[0], n: length}) |
                   map("\(.state):\(.n)") | join(", "))
              end
          ) + "\n" +
          "- **Diff:** +\(.additions // 0) / -\(.deletions // 0) across \(.changedFiles // 0) file(s)\n" +
          "- **Comments:** \(.comments | length)\n" +
          "- **Labels:** " + (if (.labels | length) > 0 then ([.labels[].name] | join(", ")) else "_none_" end) + "\n" +
          "\n" +
          (if (.body // "" | length) > 0 then .body else "_(no body)_" end) +
          "\n\n---\n"
        '
    fi
} > "$tmp"

mv "$tmp" "$out"
trap - EXIT
echo "[update-open-prs] wrote ${out} (${count} open PR(s))"
