# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_headless_wrappers", use_symbols = TRUE, package_name = "headless")

#' @usage NULL
#' @useDynLib headless, .registration = TRUE
NULL

is_null <- function(value) .Call(wrap__is_null, value)


# nolint end
