
# It is the intention that this will be generated by the rust extendr_module! in due course.
setClass("Person", representation( pointer = "externalptr" ) )

# see https://dirk.eddelbuettel.com/code/rcpp/Rcpp-modules.pdf

setMethod("$", "Person", function(self, name) {
    function(...) .Call(paste("__wrap_Person_", name), self@pointer)
} )

setMethod("initialize", "Person", function(.Object, ...) {
    .Object@pointer <- .Call("__wrap_Person_new", ...)
    .Object
} )
